DROP TABLE DOMICILIOS IF EXISTS;
DROP TABLE PACIENTES IF EXISTS;

CREATE TABLE DOMICILIOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
CALLE VARCHAR(25) NOT NULL,
NUMERO INT NOT NULL,
LOCALIDAD VARCHAR(25) NOT NULL,
PROVINCIA VARCHAR(25) NOT NULL
);

CREATE TABLE PACIENTES(
ID INT AUTO_INCREMENT PRIMARY KEY,
APELLIDO VARCHAR(25) NOT NULL,
NOMBRE VARCHAR(25) NOT NULL,
DNI VARCHAR(10) NOT NULL,
FECHA_INGRESO DATE NOT NULL,
ID_DOMICILIO INT NOT NULL);

DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
NRO_MATRICULA VARCHAR(50) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL);

INSERT INTO DOMICILIOS VALUES (DEFAULT, 'SIEMPRE VIVA',123,'CABA','BUENOS AIRES');
INSERT INTO PACIENTES VALUES (DEFAULT, 'PEREZ','JUAN','45566', '2024-07-15', 1);

INSERT INTO ODONTOLOGOS VALUES (DEFAULT, 456,'CARLOS','PANICO'), (DEFAULT, 789,'LUCIANA','MUELAS');